In [120]:
import numpy as np
import pandas as pd
import math

In [2]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1, cache=True)

checkpoint1

In [3]:
dict={}
i=1
for col in mnist["data"].columns:
    dict[col]=f"X{i}"
    i+=1
Data=mnist["data"]
Data.rename(columns=dict,
          inplace=True)

c:\users\rohit\appdata\local\programs\python\python39\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


In [4]:
for i in range(0,10):
    Data.insert(len(Data.columns),f"Y{i}",0,True)
Target=mnist["target"]
for i in range(0,7000):
    t=int(Target[i])
    Data.iloc[i,-10+t]=1

c:\users\rohit\appdata\local\programs\python\python39\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [5]:
Data

X1   X2   X3   X4   X5   X6   X7   X8   X9  X10  ...  Y0  Y1  Y2  Y3  \
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0   0   0   0   
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   1   0   0   0   
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0   0   0   0   
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0   1   0   0   
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0   0   0   0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ..  ..  ..  ..   
69995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0   0   0   0   
69996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0   0   0   0   
69997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0   0   0   0   
69998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0   0   0   0   
69999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0   0   0   0   

       Y4  Y5  Y6  Y7  Y8  Y9  
0       0   1   0   0   0   0  
1       0   0   0   0   0   0  
2       1   0   0   0   0   0  
3       0   0   0   0   0   0  
4       0   0   0   0   0   1  
...    ..  ..  ..  ..  ..  ..  
69995   0   0   0   0   0   0  
69996   0   0   0   0   0   0  
69997   0   0   0   0   0   0  
69998   0   0   0   0   0   0  
69999   0   0   0   0   0   0  

[70000 rows x 794 columns]

In [27]:
P=Data.iloc[0,:][4:7]

In [30]:
np.array(P)

array([0., 0., 0.])

In [31]:
a1=np.array(Data.iloc[0,:][0:784])

In [32]:
a1

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   

In [6]:
Training_Set=Data.iloc[0:5000,:]
Testing_Set=Data.iloc[5000:7000,:]

Check Point 2
Implementing forward propagations to a row of Data,
inputs:X1-X784 list , W(1),w(2)
outputs:activations of hidden layer and output layer

Creatinng W1 AND W2 of dimensions n X 785 and 10 x n+1


In [7]:
n=78

In [141]:
W1=np.random.rand(n,785)-[1/2]

In [142]:
W2=np.random.rand(10,n+1)-[1/2]

In [143]:
def g(x):
    return 1/(1+math.exp(-x))
vg=np.vectorize(g)


Sigmoid Function and sigmoid vector function

Check Point 3

In [151]:
def forward_propagation(W1,W2,data_point):
    x=np.array(data_point[0:784])
    y=np.array(data_point[784:])
    
    z1=np.dot(W1[:,1:],x)+W1[:,0]
    a1=(z1)
#     didnt add sigmoid fucntion right now 
# will add it soon 
    z2=np.dot(W2[:,1:],a1)+W2[:,0]
    a2=(z2)
    return a1,a2
    

In [152]:
P=Data.iloc[0,:]

In [153]:
forward_propagation(W1,W2,P)


(array([ -109.02600007,   446.64851324,   545.85131436,   771.36786115,
          110.39071912,  1305.47200742,   439.9417612 ,   772.66617301,
         1840.22283397,   586.06954731,  -261.57256857,    75.0202605 ,
         1666.31149484,  -419.12980021,    32.63342773,  1339.01933328,
          443.23696225,   501.18822007,  -539.8777805 , -1475.54164926,
         1125.29250992,  -175.56098327,  -570.97563938,  -259.77092599,
         -598.14457939,   709.86775165,  -698.21751258,   632.28937313,
          878.24288096,     9.31780194, -1269.59232994,   312.27750857,
         -802.23639555,  -201.59819118,   551.64740541, -1232.18879729,
           80.84485324,   234.92521035,  1115.80552863,  1286.43129969,
         -596.90965067,  -334.28464448,   329.55838558,   697.31312841,
         -522.46241271,   197.27933618,  -336.83817417,   751.95040176,
          980.12302438,  -603.02334891, -1161.73202751,  -459.31222326,
          -38.7299802 ,   882.01289788,  -286.89240778,  -290.86

checkpoint 4
creating cross entropy cost function

checkpoint 5
Applying backpropagation to get delta matrix and individual deltas


checkpoint6 
function named gradient , to give us the Delta omeas for both the matricies


checkpoint 7 creating gradient descent


checkpoint8 imlementing the above using gradient descent 


checkpoint 9 implementing batch gradient descent